### ISSUE TITLE
Can you update to 1.21,

### ISSUE THREAD

**Issue by Mist781** [2mal3/2mal3s-Recipes#39]
Hello
I wanted to put this datapack on my minecraft world but it didn't work because my world is 1.21.
Can you update to 1.21?

**Comment by Tatakei** [comment]
Go into the pack.mcmeta of the 2mal3's recipes datapack and change the "pack_format":26 to "pack_format":48

**Comment by 2mal3** [comment]
I'm working on it, but it's not that easy. Minecraft 1.21 brought some breaking changes to datapacks, so it will take some time to update everything.

**Comment by Tatakei** [comment]
It did? What changes did it bring

**Comment by 2mal3** [comment]
If you like, you can read through the previous changes in 3fbebc3 and a67cddc. If you really want to know, you can read all the "breaking" changes from 1.20.4 to 1.21.0 at https://misode.github.io/versions/. And that's just the tip of the iceberg, because the dependencies I use also needed to go through this stuff.
